[tool.poetry]
name = "pyarr"
version = "2.2.0"
description = "A Sonarr and Radarr API Wrapper"
authors = ["Steven Marks <marksie1988@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
keywords = ["sonarr", "radarr", "api", "wrapper"]
homepage = "https://github.com/totaldebug/pyarr"
repository = "https://github.com/totaldebug/pyarr"
documentation = "https://docs.totaldebug.uk/pyarr"

classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Multimedia :: Video",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.8",
    "Operating System :: OS Independent"
]
packages = [
    {include = "pyarr"}
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.21.0"
types-requests = "^2.25.11"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}
flake8 = "^3.8.4"
isort = "^5.10.0"
mypy = "^0.910"
pre-commit = "^2.15.0"

[tool.black]
line-length = 88
target_version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "pyarr"
disallow_untyped_defs = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
