---

version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workspace
    volumes:
      - /home/marksie1988/repos/pyarr:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
