---

name: CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  checkVersion:
    if: github.event_name  == 'pull_request'
    name: Check version updated
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Check if Python files changed
        id: changed-files
        uses: tj-actions/changed-files@v9
        with:
          files: |
            .py
            pyproject.toml
      - name: Check package version
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: dudo/tag_check@v1.1.1
        with:
          git_tag_prefix: v
  code-quality:
    name: Check PyArr Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install dependencies with Poetry
        run: poetry install
      - name: Check Pyarr imports
        run: poetry run isort --diff pyarr
      - name: Check Black formatting
        run: poetry run black --check pyarr
      - name: Check flake8 formatting
        run: poetry run flake8 pyarr
      - name: Check static type
        run: poetry run mypy pyarr
  build-n-publish:
    name: Build and publish PyArr 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: [code-quality]
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: ".github/release-changelog-builder.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # PyPi release steps
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Build
        run: poetry build
      - name: Publish distribution 📦 to PyPI
        run: poetry publish -u __token__ -p ${{ secrets.pypi_password }}
