name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  code-quality:
    name: 📊 Check code quality
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .devcontainer/docker-compose.yml
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Build docker images
        run: docker compose -f .devcontainer/docker-compose.yml
      - name: 🧪 Check tests are passing
        run: |
          pip install poetry nox
          nox -s test
